spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wxshop
    username: root
    password: 123456
<<<<<<< HEAD
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:db/mybatis/config.xml
=======
    driverClassName: com.mysql.cj.jdbc.Driver
>>>>>>> 4f61269714ad74f3626ee36216aab8638a9c2aa8
