package com.github.NervousOrange.wxshop.entity;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.id
     *
     * @mbg.generated Fri May 08 12:26:36 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.name
     *
     * @mbg.generated Fri May 08 12:26:36 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.tel
     *
     * @mbg.generated Fri May 08 12:26:36 CST 2020
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.avatar_url
     *
     * @mbg.generated Fri May 08 12:26:36 CST 2020
     */
    private String avatarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.created_at
     *
     * @mbg.generated Fri May 08 12:26:36 CST 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.modified_at
     *
     * @mbg.generated Fri May 08 12:26:36 CST 2020
     */
    private Date modifiedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.id
     *
     * @return the value of USER.id
     *
     * @mbg.generated Fri May 08 12:26:36 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.id
     *
     * @param id the value for USER.id
     *
     * @mbg.generated Fri May 08 12:26:36 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.name
     *
     * @return the value of USER.name
     *
     * @mbg.generated Fri May 08 12:26:36 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.name
     *
     * @param name the value for USER.name
     *
     * @mbg.generated Fri May 08 12:26:36 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.tel
     *
     * @return the value of USER.tel
     *
     * @mbg.generated Fri May 08 12:26:36 CST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.tel
     *
     * @param tel the value for USER.tel
     *
     * @mbg.generated Fri May 08 12:26:36 CST 2020
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.avatar_url
     *
     * @return the value of USER.avatar_url
     *
     * @mbg.generated Fri May 08 12:26:36 CST 2020
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.avatar_url
     *
     * @param avatarUrl the value for USER.avatar_url
     *
     * @mbg.generated Fri May 08 12:26:36 CST 2020
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.created_at
     *
     * @return the value of USER.created_at
     *
     * @mbg.generated Fri May 08 12:26:36 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.created_at
     *
     * @param createdAt the value for USER.created_at
     *
     * @mbg.generated Fri May 08 12:26:36 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.modified_at
     *
     * @return the value of USER.modified_at
     *
     * @mbg.generated Fri May 08 12:26:36 CST 2020
     */
    public Date getModifiedAt() {
        return modifiedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.modified_at
     *
     * @param modifiedAt the value for USER.modified_at
     *
     * @mbg.generated Fri May 08 12:26:36 CST 2020
     */
    public void setModifiedAt(Date modifiedAt) {
        this.modifiedAt = modifiedAt;
    }
}