spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wxshop?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

wxshop:
  order:
    version: 1.0.0

server:
  port: 8090

dubbo:
  application:
    name: wxshop-order
  registry:
    address: zookeeper://localhost:2181
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: com.github.NervousOrange.wxshop.service